// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myClassLibrary2;

#nullable disable

namespace MyClassLibrary2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250115015157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyClassLibrary2.Models.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Operand1")
                        .HasColumnType("float");

                    b.Property<double>("Operand2")
                        .HasColumnType("float");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("Result")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("MyClassLibrary2.Models.RockPaperScissors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ComputerChoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlayedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerChoice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RockPaperScissorsResults");
                });

            modelBuilder.Entity("MyClassLibrary2.Models.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime>("CalculatedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("Perimeter")
                        .HasColumnType("float");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Shapes");

                    b.HasDiscriminator<string>("ShapeType").HasValue("Shape");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyClassLibrary2.Models.Parallelogram", b =>
                {
                    b.HasBaseType("MyClassLibrary2.Models.Shape");

                    b.Property<double>("Base")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("SideLength")
                        .HasColumnType("float");

                    b.ToTable("Shapes", t =>
                        {
                            t.Property("Height")
                                .HasColumnName("Parallelogram_Height");

                            t.Property("SideLength")
                                .HasColumnName("Parallelogram_SideLength");
                        });

                    b.HasDiscriminator().HasValue("Parallelogram");
                });

            modelBuilder.Entity("MyClassLibrary2.Models.Rectangle", b =>
                {
                    b.HasBaseType("MyClassLibrary2.Models.Shape");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.ToTable("Shapes", t =>
                        {
                            t.Property("Height")
                                .HasColumnName("Rectangle_Height");
                        });

                    b.HasDiscriminator().HasValue("Rectangle");
                });

            modelBuilder.Entity("MyClassLibrary2.Models.Rhombus", b =>
                {
                    b.HasBaseType("MyClassLibrary2.Models.Shape");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("SideLength")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Rhombus");
                });

            modelBuilder.Entity("MyClassLibrary2.Models.Triangle", b =>
                {
                    b.HasBaseType("MyClassLibrary2.Models.Shape");

                    b.Property<double>("Base")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.ToTable("Shapes", t =>
                        {
                            t.Property("Base")
                                .HasColumnName("Triangle_Base");

                            t.Property("Height")
                                .HasColumnName("Triangle_Height");
                        });

                    b.HasDiscriminator().HasValue("Triangle");
                });
#pragma warning restore 612, 618
        }
    }
}
